<?php
/**
*/

/**
 */
$anonymous = '16';
$donators = array(
    'Anonymous (x '.$anonymous.')',
    'Pascal Vilarem (Maât)',
    'Vicente Salvador Cubedo',
    'Samuel Verschelde (Stormi)',
    'Frédéric Hugot',
    'Jonathan Bayle',
    'Markus Schimpf (arno911)',
    'HTJ Simons',
    'François Jaouen',
    'Josep Guallar-Esteve',
    'Daniel Le Berre',
    'Richard Neill',
    'Peter Trussel',
    'Marc Paré',
    'Dave Postles',
    'Basilio Rosa',
    'George Mitchell',
    'Louis Ramel',
    'Tomislav Jankovic',
    'Alexandre Lucazeau',
    'Michael Golden',
    'Jean Peyratout',
    'Philippe Seraphin',
    'Bernard Siaud',
    'Luis Maria Garcia Ruiperez',
    'Céline Harrand (leeloo)',
    'Ángel Jiménez Álvaro',
    'Jean-Michel Varvou (vouf)',
    'Margot Lawrence',
    'Teofilo Casares De La Iglesia',
    'Steven Hess',
    'Erwien Yustitiawan',
    'Thibaut François',
    'Bernd Deinzer',
    'Roland Gillard',
    'Dušan Pavlík',
    'Enrico Gsell',
    'Ernst Pini',
    'Dick Gevers',
    'Gonzalo Igartua',
    'Alexander Andreyev',
    'Frank Eisele',
    'Björn Olsson',
    'Lanfranco Gandolfo',
    'Gerardo Bueno Jiménez',
    'Murat Demir',
    'Николай Путроенок (nick7rus)',
    'Alfred Lang',
    'Antonio Pimentel',
    'Olivier Mergnac',
    'Eduardo Llana Ugalde',
    'Derek Jennings',
    'Brian Saunderson',
    'Abel Rodríguez Reádigos',
    'Barry Jackson',
    'Mike Burgener',
    'Jin-tong Hu',
    'Jani J Välimaa',
    'Jose Fernández Rosa',
    'Pierre Bonneau',
    'Richard Monnier',
    'Frederic Forjan',
    'Vincent Calame',
    'Renaud Michel',
    'Sahaghian',
    'Wolfgang Bornath (wobo)',
    'Werner Brinkmann',
    'Serge Moreau',
    'Jean Goujon',
    'Freddy Janssens',
    'Nico Bergmann',
    'Adrien Guichard',
    'Markus Vollmer',
    'Philippe Cherpentier',
    'Jean-François Bellanger',
    'Laurent Clerel',
    'Glen Ogilvie',
    'Jérôme Benoit',
    'Doug Lytle',
    'Hoyt Duff',
    'Henk Elbers',
    'Didier Leunen (sisopetron)',
    'Emmanuel Andry',
    'Sébastien Pinet',
    'Sébastien Guerin',
    'Tomeu Ferrer Redondo',
    'Philippe Jusseaume',
    'Thomas Lottmann',
    '姜 奕轲',
    'Raphael Vinet',
    'Pierre-Yves Dirand',
    'Yannick Le Ny',
    'Jean-jacques Barret',
    'Heiko Geier',
    'Livre Livre',
    'Patrick Charpentier',
    'Brian Hewitt',
    'Christian Prio',
    'Arnaud Gibert',
    'David Pernot (deap)',
    'Sylvain Haye',
    'Dave Null',
    'Jacques Spring',
    'Felipe Valladolid Gonzalo',
    'Rémi Verschelde (Akien)',
    'Fabrice Gaillard',
    'Jerome Martin (jmartin)',
    'Jean-Luc Versini',
    'Joao P S Carvalho',
    'Pierre Gabet',
    'Åke Mellin',
    'Laurent Espitallier',
    'Laurent Breton',
    'Fabrice Jade',
    'Julio Geraldo',
    'Patrice Riant',
    'Corrado Bove',
    'Marek Walter',
    'Stefan John',
    'Paul Dupouy',
    'Cedric Drolet',
    'Jacques Paret-gris',
    'Sreejiraj Eluvangal',
    'Rémy Clouard (shikamaru)',
    'Sandro Veronese',
    'Alain Gudefin',
    'Vasileios Karampelas',
    'Morgan Leijström (Tribun AB)',
    'Alain Lamarche',
    'Marita Launonen',
    'Distrowatch.com',
    'François Lamboley',
    'Martin Alduncin Garrido',
    'Pietr Petronov',
    'Jürgen Thurau',
    'Julia Jumeau',
    'Michael Lossin',
    'Jean-Guy Tesseraud',
    'Lucas Betschart',
    'Otto Fischer',
    'Loïc Carré',
    'Etienne Berger',
    'Michèle Lallement',
    'Didier Lallement',
    'Brent Wyatt',
    'Christian Henri Fischer',
    'Eugeniy Rozhkov',
    'Tobias Müller',
    'Michel Antoine (ptit-pol88)',
    'David Postles',
    'Tomas Kindl',
    'Александр Найдёнов',
    'Andrew Edwards',
    'Vilhjalmur Ingi Arnason',
    'Yaroslav Malushin',
    'Jacques Degois',
    'Marcus Moeller',
    'Sylvain Leterreur',
    'Andrew Hill',
    'Paul-Eric Despretz',
    'Luca Tani',
    'Guillemot Yves',
    'Philgren Jan-Gunnar',
    'Rene Hytting',
    'René Fischer',
    'Philippe Poilbarbe',
    'Gabriel Diosan',
    'Frédéric Buclin',
    'Michael Smith',
    'Robert J Greenwood',
    'Mike Crecelius',
    'Aymerich Munoz Jose Ignacio',
    'Giovanni Salvi',
    'Deri James',
    'Jesus del Castillo Baena',
    'Dominique Poirier',
    'Gilles Casetou',
    'Carlos Vives Bullejos',
    'Allan Gendelman',
    'Kimmo Suutala',
    'Martin Turner',
    'Jean-François Ramez',
    'Manuel Fernandes Alonso',
    'Richard Chonak',
    'Rogelio Jose Trujillo Moreno',
    'Kris Thomsen',
    'Mona Zehle',
    'Francesco De Crescenzo',
    'George Goslin',
    'Stephen Adrian',
    'Juan Barea Sanchez',
    'Franz Holzinger',
    'Placais',
    'Thomas Fackler (tomm.fa)',
    'Schouwen R M Van',
    'Marita Klen-Launonen (tumbeliina)',
    'Wulf Wilhelm',
    'Philippe Pieyre (pepy)',
    'Mriganka Talukdar',
    'Jan-Gunnar Pihlgren',
    'Vincent Ducastin',
    'Xavier Allain',
    'Marc Gibert',
    'Luis Chee Espinoza',
    'Mike Arnautov',
    'Jérôme Durand',
    'Chris Demaeyer',
    'Jean-Marc Sarat',
    'Peter Wiberg',
    'Michel de Mendez',
    'Andrew Toller',
    'Olaf Schnepel',
    'Dariusz Wielebinski',
    'Dieter Rogiest',
    'Marja van Waes',
    'Marzio Messora',
    'Curtis Herle',
    'Josy Pullockara',
    'Robert Riches',
    'L. C. Lawrence',
    'Gerald Sprik',
    'Bruno Vanhove',
    'Brian McNeil',
    'J. David Eisenberg',
    'Sascha Herholz',
    'Patrick Vossen',
    'ACL Consultans Corporation',
    'Joep van Ham',
    'Christian Fischer',
    'Pierre Opter',
    'Olivier Mejean (Goom)',
    'Jacques Anzeray',
    'Ondrej Hrstka',
    'Marcoi Pirotta',
    'Antonio Pessoa',
    'Frédéric Bonnaud',
    'Jose Luis Monzonis Cabrera',
    'Sylvain Goumas',
    'Jean Sié',
    'Bjarne Thomsen',
    'Daniel Pfenniger',
    'Alain Déchamps',
    'Jens Jablonski',
    'Rafal Artur Prasal',
    'Jean-Jacques Barret',
    'Johannes Balke',
    'Alexander Butler',
    'William Fischer',
    'Michael Waggoner',
    'François Millasson',
    'Alejandro Diaz Infante',
    'Marcel Sahaghian',
    'Edward Janusz',
    'Jean-Claude Colette',
    'Eduardo Castiello Armayor',
    'Jean-Francois Cayula',
    'Angelika Furrer',
    'Valentin Moon',
    'Jean Derouet',
    'Patrick Le Tiec',
    'Design D4PB',
    'Joseph Hubert',
    'Jurgen and Monika Harms',
    'Andreas Hiekel',
    'Louis Soriano',
    'Ota Akira',
    'Roger Mattson',
    'Gabor Alba',
    'Florian Siegenthaler',
    'Jacob Daniels',
    'Antoine de Chambost',
    'Rémi Chateauneu',
    'Mat Thorpe',
    'Marc Hotias',
    'Marc Montalbine',
    'Harold W Daley',
    'Alain Graveline',
    'Gianpiero Baglioni',
    'Michael Görrissen',
    'Jérémie Servel',
    'Samuel Iglesias Gonsalvez',
    'Julien Artacho Nieto',
    'Fabrice Deslandes',
    'Jason Schindler',
    'Duncan MacGregor',
    'Bjørn Kvisli',
    'François Pellegrini',
    'Jacob Daniels',
    'Udo Zeppich',
    'David Queen',
    'Heinz Luitz',
    'Rodney Blosser',
    'Eric Dietrich',
    'Jean Goujon',
    'Staale Ness',
    'Vernon Grimes III',
    'Andrey Belyaev',
    'Surik Sayadyan',
    'J. and N. Stiegler',
    'Svein Hauge',
    'M.J Thate Eo',
    'Arnaud Vacquier',
    'David Queen',
    'Guillaume Cottenceau',
    'jean-fernand tixier',
    'Dušan Pavlík',
    'Tino Gohl',
    'Fabrice DANT',
    'giorgio f lazzari',
    'James Campbell',
    'Jean-Marc Sarat',
    'Mike Arnautov',
    'Guy LAURENT',
    'Martin Turner',
    'Didier Chaigne',
    'Eduardo Castiello Armayor',
    'Bjarne Thomsen',
    'George Goslin',
    'Florian Berthol',
    'Nenad Latinović',
    'Johannes Balke',
    'Julio Geraldo',
    'Jean-Luc Versini',
    'Paul Patrick Honkakari',
    'Alejandro Lopez',
    'Pierre Opter',
    'L C Lawrence',
    'Raphael Vinet',
    'William Shields',
    'Jarle Bremnes',
    'Dieter Rogiest',
    'Jose Luis Nunez Crespi',
    'Urs Menet',
    'Liu Pow San',
    'Jurij Galickij',
    'Jean Christophe Lluch',
    'Richard Crosby',
    'Giuseppe Juri Facchinetti',
    'Adrien Guichard',
    'Luis Chee Espinoza',
    'Ivar Øines',
    'Dirk Mrosek',
    'Stephen Adrian',
    'OSWALD UND ADOLFINE KROP',
    'KINDL, TOMAS, JUDR.',
    'LYONESS EUROPE AG',
    'MME NOOT & NEE HUYGHE'
);
/* Last updated:
   Paypal: July, 26
   Bank: July, 26
   Check:
   Cash:
*/

//$html .= '<img src="/g/images/mageia_0.svg" style="position: absolute; top: 180px; width: 300px; opacity: 0.2;" />';

$orgs = array(
    array('http://www.mandrivafr.org/', 'AUFML'),
    array('http://dedibox.fr/', 'Dédibox'),
    array('http://www.gandi.net/', 'Gandi.net'),
    array('http://www.kazar.net/', 'Kazar.net'),
    array('http://www.lost-oasis.net/', 'Lost-Oasis'),
    array('http://www.mageialinux-online.org/', 'MLO'),
    array('http://nfrance.fr/', 'NFrance'),
    array('http://www.spreadshirt.com/', 'Spreadshirt'),
    array('http://zarb.org/', 'zarb.org'),
    
    // see mirrors.mageia.org
    array('http://www.upmc.fr/', 'Université Pierre et Marie Curie'),
    array('http://www.ibiblio.org/', 'The Public\'s Library and Digital Archive'),
    array('http://www.mandrivauser.de', 'Mandrivauser.de'),
    array('http://www.hs-esslingen.de/', 'Hochschule Esslingen'),
    array('http://uni-erlangen.de/', 'Universit&auml;t Erlangen-N&uuml;rnberg'),
    // mageia.supp.name?
    // fundawang.lcuc.org.cn?
    // ftp.LinuxCabal.org?
    // mageia.nautile.nc?
);


/**
 * @param array  $donators
 *
 * @return string
*/
function html_donators_list($donators,$anonymous)
{
    $count_donators = count($donators)+$anonymous-1; // -1 because 'anonymous' is count 1 more time in 'donators()'
    //$donators = array_unique($donators);
    sort($donators);

    $html = '<ul class="ty-ppl-list">';
    foreach ($donators as $p)
        $html .= sprintf('<li>%s</li>', $p);
    $html .= '</ul>';
    
    return array(
        'count' => $count_donators,
        'list' => $html
    );
}

/**
*/
function html_people_list($people)
{
    $html = '<ul class="ty-ppl-list">';
    foreach ($people as $p)
        $html .= sprintf('<li>%s</li>', $p);
    $html .= '</ul>';

    return $html;
}

/**
*/
function html_orgs_list($orgs)
{
    $html = '<ul class="ty-ppl-list twocol">';
    foreach ($orgs as $o)
        $html .= sprintf('<li><a href="%s">%s</a> %s</li>', $o[0], $o[1], @$o[2]);
    $html .= '</ul>';

    return $html;
}

